/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Date = IDL.Text;
export const PeriodEntry = IDL.Record({
  'endDate' : Date,
  'flow' : IDL.Nat,
  'symptoms' : IDL.Text,
  'startDate' : Date,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const HabitId = IDL.Nat;
export const HabitDay = IDL.Record({ 'date' : Date, 'habitId' : HabitId });
export const Habit = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const LogEntry = IDL.Record({
  'mood' : IDL.Nat,
  'studyHours' : IDL.Float64,
  'notes' : IDL.Text,
  'waterCups' : IDL.Nat,
  'sleepHours' : IDL.Float64,
  'energy' : IDL.Nat,
});
export const Profile = IDL.Record({ 'gender' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addHabit' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'addPeriodEntry' : IDL.Func([PeriodEntry], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkProfileCompletion' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'clearHabits' : IDL.Func([], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHabitCompletions' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [IDL.Opt(IDL.Vec(HabitDay))],
      ['query'],
    ),
  'getHabits' : IDL.Func([IDL.Principal], [IDL.Vec(Habit)], ['query']),
  'getLogEntry' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Opt(LogEntry)],
      ['query'],
    ),
  'getMotivationalQuote' : IDL.Func([], [IDL.Text], ['query']),
  'getPeriodEntries' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PeriodEntry)],
      ['query'],
    ),
  'getProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
  'incrementMotivationalQuoteCount' : IDL.Func([], [IDL.Nat], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markHabitComplete' : IDL.Func([HabitDay], [], []),
  'removeHabit' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'saveLogEntry' : IDL.Func([IDL.Text, LogEntry], [], []),
  'saveProfile' : IDL.Func([Profile], [], []),
  'unmarkHabitCompletion' : IDL.Func([HabitDay], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Date = IDL.Text;
  const PeriodEntry = IDL.Record({
    'endDate' : Date,
    'flow' : IDL.Nat,
    'symptoms' : IDL.Text,
    'startDate' : Date,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const HabitId = IDL.Nat;
  const HabitDay = IDL.Record({ 'date' : Date, 'habitId' : HabitId });
  const Habit = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const LogEntry = IDL.Record({
    'mood' : IDL.Nat,
    'studyHours' : IDL.Float64,
    'notes' : IDL.Text,
    'waterCups' : IDL.Nat,
    'sleepHours' : IDL.Float64,
    'energy' : IDL.Nat,
  });
  const Profile = IDL.Record({ 'gender' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addHabit' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'addPeriodEntry' : IDL.Func([PeriodEntry], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkProfileCompletion' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'clearHabits' : IDL.Func([], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHabitCompletions' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Opt(IDL.Vec(HabitDay))],
        ['query'],
      ),
    'getHabits' : IDL.Func([IDL.Principal], [IDL.Vec(Habit)], ['query']),
    'getLogEntry' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Opt(LogEntry)],
        ['query'],
      ),
    'getMotivationalQuote' : IDL.Func([], [IDL.Text], ['query']),
    'getPeriodEntries' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PeriodEntry)],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
    'incrementMotivationalQuoteCount' : IDL.Func([], [IDL.Nat], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markHabitComplete' : IDL.Func([HabitDay], [], []),
    'removeHabit' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'saveLogEntry' : IDL.Func([IDL.Text, LogEntry], [], []),
    'saveProfile' : IDL.Func([Profile], [], []),
    'unmarkHabitCompletion' : IDL.Func([HabitDay], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };