/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Date = string;
export interface Habit { 'id' : bigint, 'name' : string }
export interface HabitDay { 'date' : Date, 'habitId' : HabitId }
export type HabitId = bigint;
export interface LogEntry {
  'mood' : bigint,
  'studyHours' : number,
  'notes' : string,
  'waterCups' : bigint,
  'sleepHours' : number,
  'energy' : bigint,
}
export interface PeriodEntry {
  'endDate' : Date,
  'flow' : bigint,
  'symptoms' : string,
  'startDate' : Date,
}
export interface Profile { 'gender' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addHabit' : ActorMethod<[string], bigint>,
  'addPeriodEntry' : ActorMethod<[PeriodEntry], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkProfileCompletion' : ActorMethod<[Principal], boolean>,
  'clearHabits' : ActorMethod<[], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHabitCompletions' : ActorMethod<
    [Principal, bigint],
    [] | [Array<HabitDay>]
  >,
  'getHabits' : ActorMethod<[Principal], Array<Habit>>,
  'getLogEntry' : ActorMethod<[Principal, string], [] | [LogEntry]>,
  'getMotivationalQuote' : ActorMethod<[], string>,
  'getPeriodEntries' : ActorMethod<[Principal], Array<PeriodEntry>>,
  'getProfile' : ActorMethod<[Principal], Profile>,
  'incrementMotivationalQuoteCount' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markHabitComplete' : ActorMethod<[HabitDay], undefined>,
  'removeHabit' : ActorMethod<[bigint], boolean>,
  'saveLogEntry' : ActorMethod<[string, LogEntry], undefined>,
  'saveProfile' : ActorMethod<[Profile], undefined>,
  'unmarkHabitCompletion' : ActorMethod<[HabitDay], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];