/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LogEntry {
    mood: bigint;
    studyHours: number;
    notes: string;
    waterCups: bigint;
    sleepHours: number;
    energy: bigint;
}
export type Date_ = string;
export interface HabitDay {
    date: Date_;
    habitId: HabitId;
}
export type HabitId = bigint;
export interface Habit {
    id: bigint;
    name: string;
}
export interface Profile {
    gender: string;
}
export interface PeriodEntry {
    endDate: Date_;
    flow: bigint;
    symptoms: string;
    startDate: Date_;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addHabit(name: string): Promise<bigint>;
    addPeriodEntry(periodEntry: PeriodEntry): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkProfileCompletion(user: Principal): Promise<boolean>;
    clearHabits(): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getHabitCompletions(user: Principal, habitId: bigint): Promise<Array<HabitDay> | null>;
    getHabits(user: Principal): Promise<Array<Habit>>;
    getLogEntry(user: Principal, date: string): Promise<LogEntry | null>;
    getMotivationalQuote(): Promise<string>;
    getPeriodEntries(user: Principal): Promise<Array<PeriodEntry>>;
    getProfile(user: Principal): Promise<Profile>;
    incrementMotivationalQuoteCount(): Promise<bigint>;
    isCallerAdmin(): Promise<boolean>;
    markHabitComplete(habitDay: HabitDay): Promise<void>;
    removeHabit(habitId: bigint): Promise<boolean>;
    saveLogEntry(date: string, logEntry: LogEntry): Promise<void>;
    saveProfile(profile: Profile): Promise<void>;
    unmarkHabitCompletion(habitDay: HabitDay): Promise<boolean>;
}
import type { HabitDay as _HabitDay, LogEntry as _LogEntry, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addHabit(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addHabit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHabit(arg0);
            return result;
        }
    }
    async addPeriodEntry(arg0: PeriodEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPeriodEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPeriodEntry(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkProfileCompletion(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkProfileCompletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkProfileCompletion(arg0);
            return result;
        }
    }
    async clearHabits(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearHabits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearHabits();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHabitCompletions(arg0: Principal, arg1: bigint): Promise<Array<HabitDay> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHabitCompletions(arg0, arg1);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHabitCompletions(arg0, arg1);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHabits(arg0: Principal): Promise<Array<Habit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHabits(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHabits(arg0);
            return result;
        }
    }
    async getLogEntry(arg0: Principal, arg1: string): Promise<LogEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogEntry(arg0, arg1);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogEntry(arg0, arg1);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMotivationalQuote(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getMotivationalQuote();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMotivationalQuote();
            return result;
        }
    }
    async getPeriodEntries(arg0: Principal): Promise<Array<PeriodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPeriodEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPeriodEntries(arg0);
            return result;
        }
    }
    async getProfile(arg0: Principal): Promise<Profile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return result;
        }
    }
    async incrementMotivationalQuoteCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementMotivationalQuoteCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementMotivationalQuoteCount();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markHabitComplete(arg0: HabitDay): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markHabitComplete(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markHabitComplete(arg0);
            return result;
        }
    }
    async removeHabit(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeHabit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeHabit(arg0);
            return result;
        }
    }
    async saveLogEntry(arg0: string, arg1: LogEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveLogEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveLogEntry(arg0, arg1);
            return result;
        }
    }
    async saveProfile(arg0: Profile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProfile(arg0);
            return result;
        }
    }
    async unmarkHabitCompletion(arg0: HabitDay): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unmarkHabitCompletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unmarkHabitCompletion(arg0);
            return result;
        }
    }
}
function from_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_HabitDay>]): Array<HabitDay> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LogEntry]): LogEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
